name: WC_Deploy
on:
  workflow_call:
    secrets:
      GHA_PAT:
        required: true
  # Allows you to run this workflow manually from the Actions tab
    inputs:
      PROJECT_NAME:
        description: 'Project Level'
        required: true
        type: string
      APP_NAME:
        description: 'Application Name'
        required: true
        type: string
      RELEASE_BRANCH:
        description: 'Select the service release branch to checkout the code repo'
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
