name: WC_Deploy
on:
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        description: 'Project Level'
        required: true
        type: string
      APP_NAME:
        description: 'Application Name'
        required: true
        type: string
      RELEASE_BRANCH:
        description: 'Select the service release branch to checkout the code repo'
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  process_app_name:
    runs-on: ubuntu-latest

    steps:
    - name: Set up variables
      id: vars
      run: |
        echo "::set-output name=processed_name::${{ github.event.inputs.APP_NAME//./d }}"
      shell: bash

    - name: Display processed APP_NAME
      run: echo "Processed APP_NAME: ${{ steps.vars.outputs.processed_name }}"
